/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TaxComplianceRouteImport } from './routes/tax-compliance'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrintingBrandingRouteImport } from './routes/printing-branding'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as IctServicesRouteImport } from './routes/ict-services'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BusinessRegistrationRouteImport } from './routes/business-registration'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PortalRegisterRouteImport } from './routes/portal.register'
import { Route as PortalProjectsRouteImport } from './routes/portal.projects'
import { Route as PortalProfileRouteImport } from './routes/portal.profile'
import { Route as PortalPaymentsRouteImport } from './routes/portal.payments'
import { Route as PortalMessagesRouteImport } from './routes/portal.messages'
import { Route as PortalLoginRouteImport } from './routes/portal.login'
import { Route as PortalForgotPasswordRouteImport } from './routes/portal.forgot-password'
import { Route as PortalDocumentsRouteImport } from './routes/portal.documents'
import { Route as PortalDashboardRouteImport } from './routes/portal.dashboard'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminProjectUpdatesRouteImport } from './routes/admin.project-updates'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminInvoicesRouteImport } from './routes/admin.invoices'
import { Route as AdminDocumentsRouteImport } from './routes/admin.documents'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as PortalQuotationsIndexRouteImport } from './routes/portal.quotations.index'
import { Route as PortalEnquiriesIndexRouteImport } from './routes/portal.enquiries.index'
import { Route as AdminQuotationsIndexRouteImport } from './routes/admin.quotations.index'
import { Route as AdminEnquiriesIndexRouteImport } from './routes/admin.enquiries.index'
import { Route as PortalQuotationsQuotationIdRouteImport } from './routes/portal.quotations.$quotationId'
import { Route as PortalProjectsProjectIdRouteImport } from './routes/portal.projects.$projectId'
import { Route as PortalInvoicesInvoiceIdRouteImport } from './routes/portal.invoices.$invoiceId'
import { Route as PortalEnquiriesNewRouteImport } from './routes/portal.enquiries.new'
import { Route as PortalEnquiriesEnquiryIdRouteImport } from './routes/portal.enquiries.$enquiryId'
import { Route as AdminQuotationsNewRouteImport } from './routes/admin.quotations.new'
import { Route as AdminQuotationsQuotationIdRouteImport } from './routes/admin.quotations.$quotationId'
import { Route as AdminProjectsNewRouteImport } from './routes/admin.projects.new'
import { Route as AdminProjectsProjectIdRouteImport } from './routes/admin.projects.$projectId'
import { Route as AdminInvoicesInvoiceIdRouteImport } from './routes/admin.invoices.$invoiceId'
import { Route as AdminEnquiriesEnquiryIdRouteImport } from './routes/admin.enquiries.$enquiryId'
import { Route as AdminDocumentsDocumentIdRouteImport } from './routes/admin.documents.$documentId'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxComplianceRoute = TaxComplianceRouteImport.update({
  id: '/tax-compliance',
  path: '/tax-compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintingBrandingRoute = PrintingBrandingRouteImport.update({
  id: '/printing-branding',
  path: '/printing-branding',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const IctServicesRoute = IctServicesRouteImport.update({
  id: '/ict-services',
  path: '/ict-services',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRegistrationRoute = BusinessRegistrationRouteImport.update({
  id: '/business-registration',
  path: '/business-registration',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PortalRegisterRoute = PortalRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProjectsRoute = PortalProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPaymentsRoute = PortalPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMessagesRoute = PortalMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PortalRoute,
} as any)
const PortalForgotPasswordRoute = PortalForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDocumentsRoute = PortalDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PortalRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectUpdatesRoute = AdminProjectUpdatesRouteImport.update({
  id: '/project-updates',
  path: '/project-updates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInvoicesRoute = AdminInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortalQuotationsIndexRoute = PortalQuotationsIndexRouteImport.update({
  id: '/quotations/',
  path: '/quotations/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalEnquiriesIndexRoute = PortalEnquiriesIndexRouteImport.update({
  id: '/enquiries/',
  path: '/enquiries/',
  getParentRoute: () => PortalRoute,
} as any)
const AdminQuotationsIndexRoute = AdminQuotationsIndexRouteImport.update({
  id: '/quotations/',
  path: '/quotations/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnquiriesIndexRoute = AdminEnquiriesIndexRouteImport.update({
  id: '/enquiries/',
  path: '/enquiries/',
  getParentRoute: () => AdminRoute,
} as any)
const PortalQuotationsQuotationIdRoute =
  PortalQuotationsQuotationIdRouteImport.update({
    id: '/quotations/$quotationId',
    path: '/quotations/$quotationId',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalProjectsProjectIdRoute = PortalProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => PortalProjectsRoute,
} as any)
const PortalInvoicesInvoiceIdRoute = PortalInvoicesInvoiceIdRouteImport.update({
  id: '/invoices/$invoiceId',
  path: '/invoices/$invoiceId',
  getParentRoute: () => PortalRoute,
} as any)
const PortalEnquiriesNewRoute = PortalEnquiriesNewRouteImport.update({
  id: '/enquiries/new',
  path: '/enquiries/new',
  getParentRoute: () => PortalRoute,
} as any)
const PortalEnquiriesEnquiryIdRoute =
  PortalEnquiriesEnquiryIdRouteImport.update({
    id: '/enquiries/$enquiryId',
    path: '/enquiries/$enquiryId',
    getParentRoute: () => PortalRoute,
  } as any)
const AdminQuotationsNewRoute = AdminQuotationsNewRouteImport.update({
  id: '/quotations/new',
  path: '/quotations/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuotationsQuotationIdRoute =
  AdminQuotationsQuotationIdRouteImport.update({
    id: '/quotations/$quotationId',
    path: '/quotations/$quotationId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminProjectsNewRoute = AdminProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminProjectsRoute,
} as any)
const AdminProjectsProjectIdRoute = AdminProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AdminProjectsRoute,
} as any)
const AdminInvoicesInvoiceIdRoute = AdminInvoicesInvoiceIdRouteImport.update({
  id: '/$invoiceId',
  path: '/$invoiceId',
  getParentRoute: () => AdminInvoicesRoute,
} as any)
const AdminEnquiriesEnquiryIdRoute = AdminEnquiriesEnquiryIdRouteImport.update({
  id: '/enquiries/$enquiryId',
  path: '/enquiries/$enquiryId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentsDocumentIdRoute =
  AdminDocumentsDocumentIdRouteImport.update({
    id: '/$documentId',
    path: '/$documentId',
    getParentRoute: () => AdminDocumentsRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/business-registration': typeof BusinessRegistrationRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/ict-services': typeof IctServicesRoute
  '/mcp': typeof McpRoute
  '/portal': typeof PortalRouteWithChildren
  '/printing-branding': typeof PrintingBrandingRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tax-compliance': typeof TaxComplianceRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/documents': typeof AdminDocumentsRouteWithChildren
  '/admin/invoices': typeof AdminInvoicesRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/project-updates': typeof AdminProjectUpdatesRoute
  '/admin/projects': typeof AdminProjectsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/forgot-password': typeof PortalForgotPasswordRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/payments': typeof PortalPaymentsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/projects': typeof PortalProjectsRouteWithChildren
  '/portal/register': typeof PortalRegisterRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/documents/$documentId': typeof AdminDocumentsDocumentIdRoute
  '/admin/enquiries/$enquiryId': typeof AdminEnquiriesEnquiryIdRoute
  '/admin/invoices/$invoiceId': typeof AdminInvoicesInvoiceIdRoute
  '/admin/projects/$projectId': typeof AdminProjectsProjectIdRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/quotations/$quotationId': typeof AdminQuotationsQuotationIdRoute
  '/admin/quotations/new': typeof AdminQuotationsNewRoute
  '/portal/enquiries/$enquiryId': typeof PortalEnquiriesEnquiryIdRoute
  '/portal/enquiries/new': typeof PortalEnquiriesNewRoute
  '/portal/invoices/$invoiceId': typeof PortalInvoicesInvoiceIdRoute
  '/portal/projects/$projectId': typeof PortalProjectsProjectIdRoute
  '/portal/quotations/$quotationId': typeof PortalQuotationsQuotationIdRoute
  '/admin/enquiries/': typeof AdminEnquiriesIndexRoute
  '/admin/quotations/': typeof AdminQuotationsIndexRoute
  '/portal/enquiries/': typeof PortalEnquiriesIndexRoute
  '/portal/quotations/': typeof PortalQuotationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/business-registration': typeof BusinessRegistrationRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/ict-services': typeof IctServicesRoute
  '/mcp': typeof McpRoute
  '/printing-branding': typeof PrintingBrandingRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tax-compliance': typeof TaxComplianceRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/documents': typeof AdminDocumentsRouteWithChildren
  '/admin/invoices': typeof AdminInvoicesRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/project-updates': typeof AdminProjectUpdatesRoute
  '/admin/projects': typeof AdminProjectsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/forgot-password': typeof PortalForgotPasswordRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/payments': typeof PortalPaymentsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/projects': typeof PortalProjectsRouteWithChildren
  '/portal/register': typeof PortalRegisterRoute
  '/admin': typeof AdminIndexRoute
  '/portal': typeof PortalIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/documents/$documentId': typeof AdminDocumentsDocumentIdRoute
  '/admin/enquiries/$enquiryId': typeof AdminEnquiriesEnquiryIdRoute
  '/admin/invoices/$invoiceId': typeof AdminInvoicesInvoiceIdRoute
  '/admin/projects/$projectId': typeof AdminProjectsProjectIdRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/quotations/$quotationId': typeof AdminQuotationsQuotationIdRoute
  '/admin/quotations/new': typeof AdminQuotationsNewRoute
  '/portal/enquiries/$enquiryId': typeof PortalEnquiriesEnquiryIdRoute
  '/portal/enquiries/new': typeof PortalEnquiriesNewRoute
  '/portal/invoices/$invoiceId': typeof PortalInvoicesInvoiceIdRoute
  '/portal/projects/$projectId': typeof PortalProjectsProjectIdRoute
  '/portal/quotations/$quotationId': typeof PortalQuotationsQuotationIdRoute
  '/admin/enquiries': typeof AdminEnquiriesIndexRoute
  '/admin/quotations': typeof AdminQuotationsIndexRoute
  '/portal/enquiries': typeof PortalEnquiriesIndexRoute
  '/portal/quotations': typeof PortalQuotationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/business-registration': typeof BusinessRegistrationRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/ict-services': typeof IctServicesRoute
  '/mcp': typeof McpRoute
  '/portal': typeof PortalRouteWithChildren
  '/printing-branding': typeof PrintingBrandingRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tax-compliance': typeof TaxComplianceRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/documents': typeof AdminDocumentsRouteWithChildren
  '/admin/invoices': typeof AdminInvoicesRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/project-updates': typeof AdminProjectUpdatesRoute
  '/admin/projects': typeof AdminProjectsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/portal/dashboard': typeof PortalDashboardRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/forgot-password': typeof PortalForgotPasswordRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/payments': typeof PortalPaymentsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/projects': typeof PortalProjectsRouteWithChildren
  '/portal/register': typeof PortalRegisterRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/documents/$documentId': typeof AdminDocumentsDocumentIdRoute
  '/admin/enquiries/$enquiryId': typeof AdminEnquiriesEnquiryIdRoute
  '/admin/invoices/$invoiceId': typeof AdminInvoicesInvoiceIdRoute
  '/admin/projects/$projectId': typeof AdminProjectsProjectIdRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/quotations/$quotationId': typeof AdminQuotationsQuotationIdRoute
  '/admin/quotations/new': typeof AdminQuotationsNewRoute
  '/portal/enquiries/$enquiryId': typeof PortalEnquiriesEnquiryIdRoute
  '/portal/enquiries/new': typeof PortalEnquiriesNewRoute
  '/portal/invoices/$invoiceId': typeof PortalInvoicesInvoiceIdRoute
  '/portal/projects/$projectId': typeof PortalProjectsProjectIdRoute
  '/portal/quotations/$quotationId': typeof PortalQuotationsQuotationIdRoute
  '/admin/enquiries/': typeof AdminEnquiriesIndexRoute
  '/admin/quotations/': typeof AdminQuotationsIndexRoute
  '/portal/enquiries/': typeof PortalEnquiriesIndexRoute
  '/portal/quotations/': typeof PortalQuotationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/business-registration'
    | '/contact'
    | '/forgot-password'
    | '/ict-services'
    | '/mcp'
    | '/portal'
    | '/printing-branding'
    | '/privacy'
    | '/quote'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/tax-compliance'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/clients'
    | '/admin/dashboard'
    | '/admin/documents'
    | '/admin/invoices'
    | '/admin/payments'
    | '/admin/project-updates'
    | '/admin/projects'
    | '/admin/settings'
    | '/portal/dashboard'
    | '/portal/documents'
    | '/portal/forgot-password'
    | '/portal/login'
    | '/portal/messages'
    | '/portal/payments'
    | '/portal/profile'
    | '/portal/projects'
    | '/portal/register'
    | '/admin/'
    | '/portal/'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/documents/$documentId'
    | '/admin/enquiries/$enquiryId'
    | '/admin/invoices/$invoiceId'
    | '/admin/projects/$projectId'
    | '/admin/projects/new'
    | '/admin/quotations/$quotationId'
    | '/admin/quotations/new'
    | '/portal/enquiries/$enquiryId'
    | '/portal/enquiries/new'
    | '/portal/invoices/$invoiceId'
    | '/portal/projects/$projectId'
    | '/portal/quotations/$quotationId'
    | '/admin/enquiries/'
    | '/admin/quotations/'
    | '/portal/enquiries/'
    | '/portal/quotations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/business-registration'
    | '/contact'
    | '/forgot-password'
    | '/ict-services'
    | '/mcp'
    | '/printing-branding'
    | '/privacy'
    | '/quote'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/tax-compliance'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/clients'
    | '/admin/dashboard'
    | '/admin/documents'
    | '/admin/invoices'
    | '/admin/payments'
    | '/admin/project-updates'
    | '/admin/projects'
    | '/admin/settings'
    | '/portal/dashboard'
    | '/portal/documents'
    | '/portal/forgot-password'
    | '/portal/login'
    | '/portal/messages'
    | '/portal/payments'
    | '/portal/profile'
    | '/portal/projects'
    | '/portal/register'
    | '/admin'
    | '/portal'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/documents/$documentId'
    | '/admin/enquiries/$enquiryId'
    | '/admin/invoices/$invoiceId'
    | '/admin/projects/$projectId'
    | '/admin/projects/new'
    | '/admin/quotations/$quotationId'
    | '/admin/quotations/new'
    | '/portal/enquiries/$enquiryId'
    | '/portal/enquiries/new'
    | '/portal/invoices/$invoiceId'
    | '/portal/projects/$projectId'
    | '/portal/quotations/$quotationId'
    | '/admin/enquiries'
    | '/admin/quotations'
    | '/portal/enquiries'
    | '/portal/quotations'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/business-registration'
    | '/contact'
    | '/forgot-password'
    | '/ict-services'
    | '/mcp'
    | '/portal'
    | '/printing-branding'
    | '/privacy'
    | '/quote'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/tax-compliance'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/clients'
    | '/admin/dashboard'
    | '/admin/documents'
    | '/admin/invoices'
    | '/admin/payments'
    | '/admin/project-updates'
    | '/admin/projects'
    | '/admin/settings'
    | '/portal/dashboard'
    | '/portal/documents'
    | '/portal/forgot-password'
    | '/portal/login'
    | '/portal/messages'
    | '/portal/payments'
    | '/portal/profile'
    | '/portal/projects'
    | '/portal/register'
    | '/admin/'
    | '/portal/'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/documents/$documentId'
    | '/admin/enquiries/$enquiryId'
    | '/admin/invoices/$invoiceId'
    | '/admin/projects/$projectId'
    | '/admin/projects/new'
    | '/admin/quotations/$quotationId'
    | '/admin/quotations/new'
    | '/portal/enquiries/$enquiryId'
    | '/portal/enquiries/new'
    | '/portal/invoices/$invoiceId'
    | '/portal/projects/$projectId'
    | '/portal/quotations/$quotationId'
    | '/admin/enquiries/'
    | '/admin/quotations/'
    | '/portal/enquiries/'
    | '/portal/quotations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BusinessRegistrationRoute: typeof BusinessRegistrationRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  IctServicesRoute: typeof IctServicesRoute
  McpRoute: typeof McpRoute
  PortalRoute: typeof PortalRouteWithChildren
  PrintingBrandingRoute: typeof PrintingBrandingRoute
  PrivacyRoute: typeof PrivacyRoute
  QuoteRoute: typeof QuoteRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TaxComplianceRoute: typeof TaxComplianceRoute
  TermsRoute: typeof TermsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax-compliance': {
      id: '/tax-compliance'
      path: '/tax-compliance'
      fullPath: '/tax-compliance'
      preLoaderRoute: typeof TaxComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/printing-branding': {
      id: '/printing-branding'
      path: '/printing-branding'
      fullPath: '/printing-branding'
      preLoaderRoute: typeof PrintingBrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ict-services': {
      id: '/ict-services'
      path: '/ict-services'
      fullPath: '/ict-services'
      preLoaderRoute: typeof IctServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-registration': {
      id: '/business-registration'
      path: '/business-registration'
      fullPath: '/business-registration'
      preLoaderRoute: typeof BusinessRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/portal/register': {
      id: '/portal/register'
      path: '/register'
      fullPath: '/portal/register'
      preLoaderRoute: typeof PortalRegisterRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/projects': {
      id: '/portal/projects'
      path: '/projects'
      fullPath: '/portal/projects'
      preLoaderRoute: typeof PortalProjectsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/payments': {
      id: '/portal/payments'
      path: '/payments'
      fullPath: '/portal/payments'
      preLoaderRoute: typeof PortalPaymentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/messages': {
      id: '/portal/messages'
      path: '/messages'
      fullPath: '/portal/messages'
      preLoaderRoute: typeof PortalMessagesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/forgot-password': {
      id: '/portal/forgot-password'
      path: '/forgot-password'
      fullPath: '/portal/forgot-password'
      preLoaderRoute: typeof PortalForgotPasswordRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/documents': {
      id: '/portal/documents'
      path: '/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof PortalDocumentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/dashboard': {
      id: '/portal/dashboard'
      path: '/dashboard'
      fullPath: '/portal/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/project-updates': {
      id: '/admin/project-updates'
      path: '/project-updates'
      fullPath: '/admin/project-updates'
      preLoaderRoute: typeof AdminProjectUpdatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/invoices': {
      id: '/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AdminInvoicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/quotations/': {
      id: '/portal/quotations/'
      path: '/quotations'
      fullPath: '/portal/quotations/'
      preLoaderRoute: typeof PortalQuotationsIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/enquiries/': {
      id: '/portal/enquiries/'
      path: '/enquiries'
      fullPath: '/portal/enquiries/'
      preLoaderRoute: typeof PortalEnquiriesIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/quotations/': {
      id: '/admin/quotations/'
      path: '/quotations'
      fullPath: '/admin/quotations/'
      preLoaderRoute: typeof AdminQuotationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enquiries/': {
      id: '/admin/enquiries/'
      path: '/enquiries'
      fullPath: '/admin/enquiries/'
      preLoaderRoute: typeof AdminEnquiriesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/portal/quotations/$quotationId': {
      id: '/portal/quotations/$quotationId'
      path: '/quotations/$quotationId'
      fullPath: '/portal/quotations/$quotationId'
      preLoaderRoute: typeof PortalQuotationsQuotationIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/projects/$projectId': {
      id: '/portal/projects/$projectId'
      path: '/$projectId'
      fullPath: '/portal/projects/$projectId'
      preLoaderRoute: typeof PortalProjectsProjectIdRouteImport
      parentRoute: typeof PortalProjectsRoute
    }
    '/portal/invoices/$invoiceId': {
      id: '/portal/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/portal/invoices/$invoiceId'
      preLoaderRoute: typeof PortalInvoicesInvoiceIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/enquiries/new': {
      id: '/portal/enquiries/new'
      path: '/enquiries/new'
      fullPath: '/portal/enquiries/new'
      preLoaderRoute: typeof PortalEnquiriesNewRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/enquiries/$enquiryId': {
      id: '/portal/enquiries/$enquiryId'
      path: '/enquiries/$enquiryId'
      fullPath: '/portal/enquiries/$enquiryId'
      preLoaderRoute: typeof PortalEnquiriesEnquiryIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/admin/quotations/new': {
      id: '/admin/quotations/new'
      path: '/quotations/new'
      fullPath: '/admin/quotations/new'
      preLoaderRoute: typeof AdminQuotationsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quotations/$quotationId': {
      id: '/admin/quotations/$quotationId'
      path: '/quotations/$quotationId'
      fullPath: '/admin/quotations/$quotationId'
      preLoaderRoute: typeof AdminQuotationsQuotationIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects/new': {
      id: '/admin/projects/new'
      path: '/new'
      fullPath: '/admin/projects/new'
      preLoaderRoute: typeof AdminProjectsNewRouteImport
      parentRoute: typeof AdminProjectsRoute
    }
    '/admin/projects/$projectId': {
      id: '/admin/projects/$projectId'
      path: '/$projectId'
      fullPath: '/admin/projects/$projectId'
      preLoaderRoute: typeof AdminProjectsProjectIdRouteImport
      parentRoute: typeof AdminProjectsRoute
    }
    '/admin/invoices/$invoiceId': {
      id: '/admin/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/admin/invoices/$invoiceId'
      preLoaderRoute: typeof AdminInvoicesInvoiceIdRouteImport
      parentRoute: typeof AdminInvoicesRoute
    }
    '/admin/enquiries/$enquiryId': {
      id: '/admin/enquiries/$enquiryId'
      path: '/enquiries/$enquiryId'
      fullPath: '/admin/enquiries/$enquiryId'
      preLoaderRoute: typeof AdminEnquiriesEnquiryIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/documents/$documentId': {
      id: '/admin/documents/$documentId'
      path: '/$documentId'
      fullPath: '/admin/documents/$documentId'
      preLoaderRoute: typeof AdminDocumentsDocumentIdRouteImport
      parentRoute: typeof AdminDocumentsRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminDocumentsRouteChildren {
  AdminDocumentsDocumentIdRoute: typeof AdminDocumentsDocumentIdRoute
}

const AdminDocumentsRouteChildren: AdminDocumentsRouteChildren = {
  AdminDocumentsDocumentIdRoute: AdminDocumentsDocumentIdRoute,
}

const AdminDocumentsRouteWithChildren = AdminDocumentsRoute._addFileChildren(
  AdminDocumentsRouteChildren,
)

interface AdminInvoicesRouteChildren {
  AdminInvoicesInvoiceIdRoute: typeof AdminInvoicesInvoiceIdRoute
}

const AdminInvoicesRouteChildren: AdminInvoicesRouteChildren = {
  AdminInvoicesInvoiceIdRoute: AdminInvoicesInvoiceIdRoute,
}

const AdminInvoicesRouteWithChildren = AdminInvoicesRoute._addFileChildren(
  AdminInvoicesRouteChildren,
)

interface AdminProjectsRouteChildren {
  AdminProjectsProjectIdRoute: typeof AdminProjectsProjectIdRoute
  AdminProjectsNewRoute: typeof AdminProjectsNewRoute
}

const AdminProjectsRouteChildren: AdminProjectsRouteChildren = {
  AdminProjectsProjectIdRoute: AdminProjectsProjectIdRoute,
  AdminProjectsNewRoute: AdminProjectsNewRoute,
}

const AdminProjectsRouteWithChildren = AdminProjectsRoute._addFileChildren(
  AdminProjectsRouteChildren,
)

interface AdminRouteChildren {
  AdminClientsRoute: typeof AdminClientsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDocumentsRoute: typeof AdminDocumentsRouteWithChildren
  AdminInvoicesRoute: typeof AdminInvoicesRouteWithChildren
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProjectUpdatesRoute: typeof AdminProjectUpdatesRoute
  AdminProjectsRoute: typeof AdminProjectsRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEnquiriesEnquiryIdRoute: typeof AdminEnquiriesEnquiryIdRoute
  AdminQuotationsQuotationIdRoute: typeof AdminQuotationsQuotationIdRoute
  AdminQuotationsNewRoute: typeof AdminQuotationsNewRoute
  AdminEnquiriesIndexRoute: typeof AdminEnquiriesIndexRoute
  AdminQuotationsIndexRoute: typeof AdminQuotationsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClientsRoute: AdminClientsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDocumentsRoute: AdminDocumentsRouteWithChildren,
  AdminInvoicesRoute: AdminInvoicesRouteWithChildren,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProjectUpdatesRoute: AdminProjectUpdatesRoute,
  AdminProjectsRoute: AdminProjectsRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEnquiriesEnquiryIdRoute: AdminEnquiriesEnquiryIdRoute,
  AdminQuotationsQuotationIdRoute: AdminQuotationsQuotationIdRoute,
  AdminQuotationsNewRoute: AdminQuotationsNewRoute,
  AdminEnquiriesIndexRoute: AdminEnquiriesIndexRoute,
  AdminQuotationsIndexRoute: AdminQuotationsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PortalProjectsRouteChildren {
  PortalProjectsProjectIdRoute: typeof PortalProjectsProjectIdRoute
}

const PortalProjectsRouteChildren: PortalProjectsRouteChildren = {
  PortalProjectsProjectIdRoute: PortalProjectsProjectIdRoute,
}

const PortalProjectsRouteWithChildren = PortalProjectsRoute._addFileChildren(
  PortalProjectsRouteChildren,
)

interface PortalRouteChildren {
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalDocumentsRoute: typeof PortalDocumentsRoute
  PortalForgotPasswordRoute: typeof PortalForgotPasswordRoute
  PortalLoginRoute: typeof PortalLoginRoute
  PortalMessagesRoute: typeof PortalMessagesRoute
  PortalPaymentsRoute: typeof PortalPaymentsRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalProjectsRoute: typeof PortalProjectsRouteWithChildren
  PortalRegisterRoute: typeof PortalRegisterRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalEnquiriesEnquiryIdRoute: typeof PortalEnquiriesEnquiryIdRoute
  PortalEnquiriesNewRoute: typeof PortalEnquiriesNewRoute
  PortalInvoicesInvoiceIdRoute: typeof PortalInvoicesInvoiceIdRoute
  PortalQuotationsQuotationIdRoute: typeof PortalQuotationsQuotationIdRoute
  PortalEnquiriesIndexRoute: typeof PortalEnquiriesIndexRoute
  PortalQuotationsIndexRoute: typeof PortalQuotationsIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalDashboardRoute: PortalDashboardRoute,
  PortalDocumentsRoute: PortalDocumentsRoute,
  PortalForgotPasswordRoute: PortalForgotPasswordRoute,
  PortalLoginRoute: PortalLoginRoute,
  PortalMessagesRoute: PortalMessagesRoute,
  PortalPaymentsRoute: PortalPaymentsRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalProjectsRoute: PortalProjectsRouteWithChildren,
  PortalRegisterRoute: PortalRegisterRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalEnquiriesEnquiryIdRoute: PortalEnquiriesEnquiryIdRoute,
  PortalEnquiriesNewRoute: PortalEnquiriesNewRoute,
  PortalInvoicesInvoiceIdRoute: PortalInvoicesInvoiceIdRoute,
  PortalQuotationsQuotationIdRoute: PortalQuotationsQuotationIdRoute,
  PortalEnquiriesIndexRoute: PortalEnquiriesIndexRoute,
  PortalQuotationsIndexRoute: PortalQuotationsIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BusinessRegistrationRoute: BusinessRegistrationRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  IctServicesRoute: IctServicesRoute,
  McpRoute: McpRoute,
  PortalRoute: PortalRouteWithChildren,
  PrintingBrandingRoute: PrintingBrandingRoute,
  PrivacyRoute: PrivacyRoute,
  QuoteRoute: QuoteRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TaxComplianceRoute: TaxComplianceRoute,
  TermsRoute: TermsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
