// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://isiqbrdytgpkgtgrjzwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzaXFicmR5dGdwa2d0Z3JqendrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM5NzYwMzYsImV4cCI6MjA5OTU1MjAzNn0.TNNG_lnWHuWgeGGSix2d9hIq3qQrT7x4ouRb_sidWcI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});